name: Update schedule

on:
  schedule:
    - cron: "0 6 * * *"   # каждый день в 6 утра по UTC
  workflow_dispatch:       # ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Run script
        run: python script.py

      - name: Commit schedule.ics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add schedule.ics || true
          git commit -m "update schedule.ics" || echo "No changes to commit"
          git push
          git commit -m "Update schedule" || echo "No changes"
          git push || echo "Push failed"
